#!/bin/bash/env bash
# Pass a directory containing *.bam, *.vcf files as a single argument

# Function prints proper usage of script if there is misuse
usage() {
    echo "Usage: $0 [-d <valid directory>] [-t <optional integer>]"    
    exit 1; # Exit with an error
}

# Parse through provided options from command line
while getopts :d:t: o; do
    case "${o}" in
        d) 
            directory=${OPTARG}
            # Make sure -d option is a directory 
            [[ -d "$directory" ]] || usage 
            ;;

        t) 
            threshold=${OPTARG}
            # Make sure -t option is an integer
            [[ $threshold =~ [0-9]+ ]] || usage 
            ;;

        * | h) 
            usage # Print usage prompt
            exit 0 # Exit without errors
            ;;
    esac
done

# Make sure the -d (directory) option is provided
if [[ -z "$directory" ]]; then
    usage
fi

# If no -t (threshhold) provided set the default to 30
if [[ -z "$threshold" ]]; then
    threshold=30
fi

# Change into the pipeline subdirectory
cd pipe

# Label the columns of the output.csv file
echo "Filename, "Position Reference Alternate", Depth Score" > output.csv

# Count total number of selected colonies in directory
echo "Counting relevant files from directory..."
total_colonies=$(ls -l "$directory"/*JGI*.vcf | wc -l | tr -d '[:space:]')
echo "$total_colonies colonies counted in submitted directory."
echo

# Initiate Counter
counter=0

echo "Collecting variants and depth metrics from each colony...."
echo "Your depth threshold is $threshold. Stop the script (Ctr-C) if this is incorrect."
echo
echo "This may take some time depending on strength of connection to the remote server."
echo
    
# Parse information from each .bam/.vcf file pair. Store in variables and export to csv.
for filename in "$directory"/*JGI*.vcf; do
    counter=$((counter + 1))
    
    depth_score="$(samtools depth "${filename%.*}.bam" | python depth.py $threshold)"
    variant_array="$(bcftools query -f '%POS %REF %ALT\n' "$filename")"
    column_name="$(basename "$filename")"

    echo "$counter/$total_colonies" # echo current/total
    echo "$column_name",\""$variant_array"\","$depth_score" >> output.csv
done

echo 
echo "Finished collecting colony information." 

# Generate visually pleasant excel file with .csv file, overwrite if it exists
if [ -f visual.xlsx ]; then

    echo "Overwriting existing visual.xlsx file..."
    rm visual.xlsx
    python generate_visual.py
    echo "Colony screening information written to visual.xlsx"

else

    python generate_visual.py
    echo "Colony screening information written to visual.xlsx"

fi

echo "Opening results in an excel table."

# Open excel file
open visual.xlsx
