#!/bin/bash/env bash
# Pass a directory containing *.bam, *.vcf files as a single argument

echo "Filename, Position_Reference_Alternate, Depth Score" > output.csv
for filename in "$1"/*JGI*.vcf; do
  bcftools query -f '%POS %REF %ALT\n' "$filename" > temp_reads.txt
  samtools depth "${filename%.*}.bam" > temp_depth.txt

  echo "Variants from Read: "$(cat temp_reads.txt)""

  echo "$(basename "$filename"),\"$(cat temp_reads.txt)\",$(python depth.py)" >> output.csv
done

if [ -f visual.xlsx ]; then
  echo "Overwriting existing visual.xlsx file..."
  echo "########################################"
  echo "Colony screening information written to \"visual.xlsx\" "
  rm visual.xlsx
  python generate_visual.py
else
  python generate_visual.py
  echo "########################################"
  echo "Colony screening information written to \"visual.xlsx\" "
fi

rm *.txt
